### ISSUE TITLE
Refine business requirements

### ISSUE THREAD

**Issue by stereohorse** [stereohorse/stream-search#1]
Let's discuss & refine requirements: https://github.com/stereohorse/stream-search/wiki/Initial-business-requirements

**Comment by Fukuro2023** [comment]
Sketch for UI
https://excalidraw.com/#json=QmcIkGkio40psBH9N5Rbx,KWi9YMw9gbdsmbOfGlHhPw

**Comment by Fukuro2023** [comment]
Shared whiteboard for our design:
https://link.excalidraw.com/l/fYaWEqEwRa/8ysxXUhr3Wd
